workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.patchpulse.app
      vars:
        XCODE_SCHEME: "App"
      node: 18
      xcode: 15.4
      cocoapods: default

    scripts:
      - name: Install npm dependencies
        script: |
          npm ci

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            CODE_SIGNING_REQUIRED=YES

      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ../../exportOptions.plist

    artifacts:
      - ios/App/build/ipa/*.ipa
      - ios/App/build/*.xcarchive
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
