workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 18
      xcode: 15.4
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Capacitor sync
        script: |
          npx cap sync ios

      - name: Pod install
        script: |
          cd ios/App && pod install --repo-update

      - name: Build
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            build

    artifacts:
      - ios/App/build/**/*
